### PR TITLE
Feat: Added navbar, Hero Section, Categories and Trending Games

### PR DESCRIPTION
**Pull request by sainath7878**
Added navbar, hero section, categories, trending in the landing page. Please review and provide feedback.

### CODE REVIEW

**Review by hsnice16 — APPROVED** [review]
Code is good, UI is great. Just one suggestion, I think, cross on Product doesn't make sense as the user can not remove a card from UI. So you can improve that, 
image

**Comment by anik31** [comment]
I will also suggest the same what @hsnice16 said. Replace the cross button with the wishlist (heart) button, it will give a good ux.

**Review by Maianki — APPROVED** [review]
Nice UI. Do the changes suggested by Himanshu and you are good to merge.

**Comment by sainath7878** [comment]
> Code is good, UI is great. Just one suggestion, I think, cross on Product doesn't make sense as the user can not remove a card from UI. So you can improve that, image

Made the changes, Added wishlist instead of dismiss as suggested by @anik31.

**Comment by sainath7878** [comment]
> I will also suggest the same what @hsnice16 said. Replace the cross button with the wishlist (heart) button, it will give a good ux.

Made the changes

**Comment by anik31** [comment]
> > I will also suggest the same what @hsnice16 said. Replace the cross button with the wishlist (heart) button, it will give a good ux.
> 
> Made the changes

Nice work. UI looks great

**Pull request merged**
