### PR TITLE
Feat: Added Sign-in and Sign-up pages

### PR DESCRIPTION
**Pull request by sainath7878**
Added the following pages to E-Commerce Site
1. Sign In
2. Sign Up

### CODE REVIEW

**Review by Maianki — APPROVED** [review]
Looks good to merge.

**Review by hsnice16 — APPROVED** [review]
The code looks good. But I think, you have not implemented all the requirements, 
image

Just implement all these requirements, and you are good to merge.

**Review by anik31 — APPROVED** [review]
Looks good.  I think centering the login box inside the body will look good. You can try it out

**Comment by sainath7878** [comment]
> Looks good. I think centering the login box inside the body will look good. You can try it out

The login form is already centered. Isn't it?

**Comment by sainath7878** [comment]
> The code looks good. But I think, you have not implemented all the requirements, image
> 
> Just implement all these requirements, and you are good to merge.

Added first name and last name. But showing and hiding Password requires JS right?

**Comment by anik31** [comment]
> > Looks good. I think centering the login box inside the body will look good. You can try it out
> 
> The login form is already centered. Isn't it?

Ya it is. Now I saw it. It is not centering vertically beacause of the body height.

**Comment by sainath7878** [comment]
> > > Looks good. I think centering the login box inside the body will look good. You can try it out
> > 
> > 
> > The login form is already centered. Isn't it?
> 
> Ya it is. Now I saw it. It is not centering vertically beacause of the body height.

Should I give it a fixed height?

**Comment by anik31** [comment]
> > > > Looks good. I think centering the login box inside the body will look good. You can try it out
> > > 
> > > 
> > > The login form is already centered. Isn't it?
> > 
> > 
> > Ya it is. Now I saw it. It is not centering vertically beacause of the body height.
> 
> Should I give it a fixed height?

Leave it for now. You can do it later.

**Comment by hsnice16** [comment]
> > The code looks good. But I think, you have not implemented all the requirements, image
> > Just implement all these requirements, and you are good to merge.
> 
> Added first name and last name. But showing and hiding Password requires JS right?

For functionality they require JS. But you can implement their UI, how they will look. If you want, you can refer to mine. https://inclusive-mart.netlify.app/pages/signup.html

**Comment by sainath7878** [comment]
> > > The code looks good. But I think, you have not implemented all the requirements, image
> > > Just implement all these requirements, and you are good to merge.
> > 
> > 
> > Added first name and last name. But showing and hiding Password requires JS right?
> 
> For functionality they require JS. But you can implement their UI, how they will look. If you want, you can refer to mine. https://inclusive-mart.netlify.app/pages/signup.html

Thank you for dropping the link. Will refer to it.

**Pull request merged**
